config:
  swagger: true
eureka:
  # 实例设置
  instance:
    # 实例主机名称
    ipAddress: 192.168.0.231
    instance-id:  192.168.0.231:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.0.231:8760/eureka/
logging:
  level:
    root: warn
    com.sbwork: info
spring:
  datasource:
    url: jdbc:mysql://192.168.0.61:3306/dr2?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: dr
    password: dr