config:
  noVerifyCode: true
  swagger: false
  db:
    create-table: true
  logback:
    outLevel: DEBUG
    fileLevel: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hy_pc_dr?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test01
    password: 123456
