config:
  logback:
    outLevel: WARN
    fileLevel: ALL
  db:
    dbs:
      #数据源a01
      proxy:
        url: jdbc:mysql://localhost:3306/pc?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: pc
        password: pc
